### ISSUE TITLE
Start 

### ISSUE THREAD

**Issue by JO-Yeonju** [youngcodej22/gitflow-practice#1]
# Contents

## Task list

- [x] html  멋있게 작성
- [x] css  쿨하게 작성
- [x] js 헉소리나게 작성

**Comment by youngcodej22** [comment]
이제 pull request  차례죠?

**Comment by youngcodej22** [comment]
done
